"""Command-line tool: grow crop plants in the plots of a layout CSV, as a Gazebo model."""

import argparse
from pathlib import Path

from agri_ugv_field.ground import ground_height, read_obj_grid
from agri_ugv_field.layout import read_layout_csv
from agri_ugv_field.plants import CROPS, merge, obj_text, PARTS, plot_mesh, vertex_normals
from agri_ugv_field.textures import draw_texture
from agri_ugv_terrain.heightfield import model_config
import numpy as np


def plants_sdf(name, meshes):
    """
    Write a static model with one visual per mesh and no collision.

    meshes maps a mesh name to its texture name. Each material shows the texture's picture
    and cuts away its transparent parts; leaves are drawn from both sides. Plants are visual
    only: the robot's physics ignores them (real plants are soft), cameras and LiDARs see them.
    """
    visuals = ''.join(f"""
      <visual name="{mesh}">
        <cast_shadows>false</cast_shadows>
        <geometry>
          <mesh><uri>meshes/{mesh}.obj</uri></mesh>
        </geometry>
        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
          <double_sided>true</double_sided>
          <pbr>
            <metal>
              <albedo_map>textures/{texture}.png</albedo_map>
              <roughness>0.8</roughness>
              <metalness>0</metalness>
            </metal>
          </pbr>
        </material>
      </visual>""" for mesh, texture in meshes.items())
    return f"""<?xml version="1.0"?>
<sdf version="1.9">
  <model name="{name}">
    <static>true</static>
    <link name="plants">{visuals}
    </link>
  </model>
</sdf>
"""


def main(argv=None):
    """Read plots and terrain, place the plants, write <output-dir>/<name>/ as a model."""
    parser = argparse.ArgumentParser(
        description='Make a Gazebo model of crop plants. The defaults grow the MuST-C field '
        'when run from the workspace folder.')
    parser.add_argument('--layout', default='src/agri_ugv_field/data/must_c_field_plots.csv',
                        help='plot layout CSV (make_field_layout)')
    parser.add_argument('--terrain-model', default='src/agri_ugv_gazebo/models/must_c_field',
                        help='terrain model folder; plants stand on its mesh')
    parser.add_argument('--name', default='must_c_plants', help='model name (letters, digits, _)')
    parser.add_argument('--output-dir', default='src/agri_ugv_gazebo/models',
                        help='folder to write the model into')
    parser.add_argument('--seed', type=int, default=1, help='random seed (same seed, same field)')
    args = parser.parse_args(argv)

    plots = [r for r in read_layout_csv(Path(args.layout).read_text()) if r['type'] == 'plot']
    terrain = Path(args.terrain_model)
    grid = read_obj_grid((terrain / 'meshes' / f'{terrain.name}.obj').read_text())

    def ground(x, y):
        return ground_height(grid, x, y)

    rng = np.random.default_rng(args.seed)
    pieces, textures, stats = {}, {}, {}
    for plot in plots:
        if plot['crop'] not in CROPS:
            raise ValueError(f'plot {plot["plot_id"]}: no parameters for crop {plot["crop"]!r}')
        crop = CROPS[plot['crop']]
        meshes, count = plot_mesh(plot, crop, ground, rng)
        for part, mesh in meshes.items():
            pieces.setdefault(crop['key'] + part, []).append(mesh)
            textures[crop['key'] + part] = PARTS[crop['shape']][part]
        plots_done, items = stats.get(crop['key'], (0, 0))
        stats[crop['key']] = (plots_done + 1, items + count)

    model_dir = Path(args.output_dir) / args.name
    for folder in ('meshes', 'textures'):
        (model_dir / folder).mkdir(parents=True, exist_ok=True)
    for texture in sorted(set(textures.values())):
        draw_texture(texture, args.seed).save(model_dir / 'textures' / f'{texture}.png')
    print(f'{model_dir}: {len(plots)} plots, seed {args.seed}')
    for crop_key, (plots_done, items) in sorted(stats.items()):
        unit = 'row strips' if crop_key in ('wheat', 'mixtures') else 'plants'
        print(f'  {crop_key:<10} {plots_done:2d} plots, {items:5d} {unit}')
    for mesh in sorted(pieces):
        vertices, uvs, faces = merge(pieces[mesh])
        path = model_dir / 'meshes' / f'{mesh}.obj'
        path.write_text(obj_text(vertices, uvs, faces, vertex_normals(vertices, faces)))
        print(f'  {mesh + ".obj":<22} {len(faces):7d} triangles, '
              f'{path.stat().st_size / 1e6:5.1f} MB')
    (model_dir / 'model.sdf').write_text(plants_sdf(args.name, dict(sorted(textures.items()))))
    (model_dir / 'model.config').write_text(model_config(
        args.name, f'crop plants for the plots of {Path(args.layout).name} on the '
        f'{terrain.name} terrain, generated by agri_ugv_field (seed {args.seed}); '
        'row spacings and plant sizes are assumed typical values for late June'))
