"""Command-line tool: turn a field trial shapefile into a plot layout CSV in the world frame."""

import argparse
from collections import Counter
from pathlib import Path

from agri_ugv_field.layout import field_layout, layout_csv, terrain_origin
import numpy as np
from pyproj import CRS, Transformer

ATTRIBUTION = ('MuST-C dataset, Chong et al., https://doi.org/10.60507/FK2/OX9XTM, '
               'CC BY 4.0')


def read_shapefile(path):
    """Return ([(points, record), ...], prj_text) for a shapefile of single-part outlines."""
    import shapefile  # pyshp (Ubuntu: python3-pyshp) has no rosdep key, so imported only here

    path = Path(path)
    prj = path.with_suffix('.prj')
    if not prj.exists():
        raise ValueError(f'{prj} is missing: the coordinate system must be stated, not guessed')
    reader = shapefile.Reader(str(path))
    names = [field[0] for field in reader.fields[1:]]   # fields[0] is the deletion flag
    shapes = []
    for shape, record in zip(reader.shapes(), reader.records()):
        if len(shape.parts) != 1:
            raise ValueError(f'outline {len(shapes)} has {len(shape.parts)} parts, expected 1')
        shapes.append((np.array(shape.points, dtype=float)[:, :2],
                       dict(zip(names, list(record)))))
    reader.close()
    return shapes, prj.read_text()


def main(argv=None):
    """Read the shapefile, convert it to the terrain's world frame, check it, write the CSV."""
    parser = argparse.ArgumentParser(description='Make a plot layout CSV from a shapefile.')
    parser.add_argument('--shapefile', required=True, help='field trial outlines (.shp + .prj)')
    parser.add_argument('--terrain-model', required=True,
                        help='terrain model folder whose model.config states the world origin')
    parser.add_argument('--output', required=True, help='CSV file to write')
    parser.add_argument('--attribution', default=ATTRIBUTION, help='source credit for the CSV')
    args = parser.parse_args(argv)

    config = Path(args.terrain_model) / 'model.config'
    crs, east, north = terrain_origin(config.read_text())
    shapes, prj_text = read_shapefile(args.shapefile)
    source_crs = CRS.from_wkt(prj_text)
    transformer = Transformer.from_crs(source_crs, crs, always_xy=True)

    def to_world(points):
        x, y = transformer.transform(points[:, 0], points[:, 1])
        return np.column_stack([np.asarray(x) - east, np.asarray(y) - north])

    boundary, plots = field_layout(shapes, to_world)
    comments = [
        f'Plot layout from {Path(args.shapefile).name} ({source_crs.name}), converted to {crs} '
        f'and shifted by the origin of the {Path(args.terrain_model).name} terrain '
        f'(E {east:.2f} N {north:.2f}): x east, y north, metres.',
        f'Source: {args.attribution}. Generated by agri_ugv_field (make_field_layout).',
        'Corners run counter-clockwise, starting where the long side begins; heading_deg is '
        'the direction of the long side (the crop rows), counter-clockwise from east.',
    ]
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(layout_csv([boundary] + plots, comments))

    entries = [boundary] + plots
    widths = [p['width'] for p in plots]
    lengths = Counter(round(p['length'], 1) for p in plots)
    headings = [p['heading_deg'] for p in plots]
    print(f'Wrote {output}: {len(plots)} plots + the trial boundary '
          f'(conversion: {transformer.description}, accuracy {transformer.accuracy} m)')
    print(f'plot width {min(widths):.3f} to {max(widths):.3f} m; '
          f'lengths (rounded to 0.1 m): {dict(sorted(lengths.items()))}')
    print(f'plot heading {min(headings):.2f} to {max(headings):.2f} deg; '
          f'boundary {boundary["width"]:.2f} x {boundary["length"]:.2f} m '
          f'at {boundary["heading_deg"]:.2f} deg')
    print(f'largest gap between first and last point: {1000 * max(e["gap"] for e in entries):.2f}'
          f' mm; deviation from a perfect rectangle: plots up to '
          f'{1000 * max(p["deviation"] for p in plots):.1f} mm, boundary '
          f'{1000 * boundary["deviation"]:.1f} mm')
    print(f'crops: {dict(Counter(p["crop"] for p in plots).most_common())}')
