"""Turn a regular grid of heights into a triangle mesh and a Gazebo model."""

import numpy as np


def check_heights(heights, spacing):
    """
    Validate a height grid and return it as a float array.

    heights[i, j] is the ground height (m) at row i and column j. Columns run
    along x and rows along y, both spaced `spacing` metres apart.
    """
    grid = np.asarray(heights, dtype=float)
    if grid.ndim != 2:
        raise ValueError(f'heights must be a 2D grid, got {grid.ndim} dimension(s)')
    if grid.shape[0] < 2 or grid.shape[1] < 2:
        raise ValueError(f'heights needs at least 2 x 2 points, got {grid.shape}')
    if not np.all(np.isfinite(grid)):
        raise ValueError('heights contains NaN or infinite values')
    if not np.isfinite(spacing) or spacing <= 0.0:
        raise ValueError(f'spacing must be a positive number, got {spacing}')
    return grid


def grid_axes(rows, cols, spacing):
    """Return the x (one per column) and y (one per row) coordinates, centred on the origin."""
    x = (np.arange(cols) - (cols - 1) / 2.0) * spacing
    y = (np.arange(rows) - (rows - 1) / 2.0) * spacing
    return x, y


def mesh_from_heights(heights, spacing):
    """
    Build a triangle mesh from a height grid, centred on the origin.

    Returns (vertices, faces): vertices is an (N, 3) array of x, y, z points,
    faces an (M, 3) array of 0-based vertex indices. Each grid cell becomes two
    triangles, listed counter-clockwise seen from above so their normals point up.
    """
    grid = check_heights(heights, spacing)
    rows, cols = grid.shape
    xx, yy = np.meshgrid(*grid_axes(rows, cols, spacing))
    vertices = np.column_stack([xx.ravel(), yy.ravel(), grid.ravel()])

    index = np.arange(rows * cols).reshape(rows, cols)
    a = index[:-1, :-1].ravel()  # corner (row i, col j)
    b = index[:-1, 1:].ravel()   # one step along +x
    c = index[1:, 1:].ravel()    # one step along +x and +y
    d = index[1:, :-1].ravel()   # one step along +y
    faces = np.concatenate([np.column_stack([a, b, c]), np.column_stack([a, c, d])])
    return vertices, faces


def vertex_normals(heights, spacing):
    """
    Return the unit surface normal at every grid point, in the same order as the vertices.

    The slope at each point comes from the height differences to its neighbours
    (central differences inside the grid, one-sided at the edges). Gazebo's physics
    engine needs a normal for every vertex of a collision mesh.
    """
    grid = check_heights(heights, spacing)
    dz_dy, dz_dx = np.gradient(grid, spacing)  # rows run along y, columns along x
    normals = np.column_stack([-dz_dx.ravel(), -dz_dy.ravel(), np.ones(grid.size)])
    return normals / np.linalg.norm(normals, axis=1, keepdims=True) + 0.0  # no '-0.0'


def cell_centre_uvs(rows, cols):
    """
    Return texture coordinates (u, v) for every grid point, in the same order as the vertices.

    The grid points are the centres of rows x cols cells and the image covers all cells, so
    point (i, j) sits at u = (j + 0.5) / cols, v = (i + 0.5) / rows. Row 0 is the south edge,
    which is the bottom of the image (v = 0), as the OBJ format expects.
    """
    v, u = np.meshgrid((np.arange(rows) + 0.5) / rows, (np.arange(cols) + 0.5) / cols,
                       indexing='ij')
    return np.column_stack([u.ravel(), v.ravel()])


def obj_text(vertices, normals, faces, uvs=None, material=None):
    """
    Write a mesh in Wavefront OBJ format, with one normal per vertex.

    Indices in the file start at 1. Each face corner refers to vertex i and normal i, and,
    when texture coordinates are given, to texture coordinate i and the material's .mtl file.
    """
    if len(normals) != len(vertices):
        raise ValueError(f'need one normal per vertex, got {len(normals)} for {len(vertices)}')
    if (uvs is None) != (material is None):
        raise ValueError('texture coordinates and material must be given together')
    if uvs is not None and len(uvs) != len(vertices):
        raise ValueError(f'need one texture coordinate per vertex, got {len(uvs)}')
    lines = ['# Generated by agri_ugv_terrain']
    if material is not None:
        lines += [f'mtllib {material}.mtl', f'usemtl {material}']
    lines += [f'v {x:.4f} {y:.4f} {z:.4f}' for x, y, z in vertices]
    lines += [f'vn {x:.4f} {y:.4f} {z:.4f}' for x, y, z in normals]
    if uvs is None:
        lines += [f'f {i + 1}//{i + 1} {j + 1}//{j + 1} {k + 1}//{k + 1}' for i, j, k in faces]
    else:
        lines += [f'vt {u:.6f} {v:.6f}' for u, v in uvs]
        lines += [f'f {i + 1}/{i + 1}/{i + 1} {j + 1}/{j + 1}/{j + 1} {k + 1}/{k + 1}/{k + 1}'
                  for i, j, k in faces]
    return '\n'.join(lines) + '\n'


def mtl_text(material, image_file):
    """Write a material (.mtl) that shows the image as the surface colour, without shine."""
    return (f'newmtl {material}\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\n'
            f'map_Kd {image_file}\n')


def model_sdf(name, mesh_file, textured=False):
    """
    Write a static Gazebo model whose collision and visual both use the mesh.

    The wheels touch exactly the surface that is shown: no simplified collision box.
    A textured mesh brings its own material (.mtl), so then no plain colour is set.
    """
    uri = f'meshes/{mesh_file}'
    colour = '' if textured else """
        <material>
          <ambient>0.45 0.35 0.25 1</ambient>
          <diffuse>0.45 0.35 0.25 1</diffuse>
        </material>"""
    return f"""<?xml version="1.0"?>
<sdf version="1.9">
  <model name="{name}">
    <static>true</static>
    <link name="link">
      <collision name="collision">
        <geometry>
          <mesh><uri>{uri}</uri></mesh>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <mesh><uri>{uri}</uri></mesh>
        </geometry>{colour}
      </visual>
    </link>
  </model>
</sdf>
"""


def model_config(name, description):
    """Write the model.config file that lets Gazebo find the model by name."""
    return f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>{description}</description>
</model>
"""
