"""Turn a regular grid of heights into a triangle mesh and a Gazebo model."""

import numpy as np


def check_heights(heights, spacing):
    """
    Validate a height grid and return it as a float array.

    heights[i, j] is the ground height (m) at row i and column j. Columns run
    along x and rows along y, both spaced `spacing` metres apart.
    """
    grid = np.asarray(heights, dtype=float)
    if grid.ndim != 2:
        raise ValueError(f'heights must be a 2D grid, got {grid.ndim} dimension(s)')
    if grid.shape[0] < 2 or grid.shape[1] < 2:
        raise ValueError(f'heights needs at least 2 x 2 points, got {grid.shape}')
    if not np.all(np.isfinite(grid)):
        raise ValueError('heights contains NaN or infinite values')
    if not np.isfinite(spacing) or spacing <= 0.0:
        raise ValueError(f'spacing must be a positive number, got {spacing}')
    return grid


def mesh_from_heights(heights, spacing):
    """
    Build a triangle mesh from a height grid, centred on the origin.

    Returns (vertices, faces): vertices is an (N, 3) array of x, y, z points,
    faces an (M, 3) array of 0-based vertex indices. Each grid cell becomes two
    triangles, listed counter-clockwise seen from above so their normals point up.
    """
    grid = check_heights(heights, spacing)
    rows, cols = grid.shape
    x = (np.arange(cols) - (cols - 1) / 2.0) * spacing
    y = (np.arange(rows) - (rows - 1) / 2.0) * spacing
    xx, yy = np.meshgrid(x, y)
    vertices = np.column_stack([xx.ravel(), yy.ravel(), grid.ravel()])

    index = np.arange(rows * cols).reshape(rows, cols)
    a = index[:-1, :-1].ravel()  # corner (row i, col j)
    b = index[:-1, 1:].ravel()   # one step along +x
    c = index[1:, 1:].ravel()    # one step along +x and +y
    d = index[1:, :-1].ravel()   # one step along +y
    faces = np.concatenate([np.column_stack([a, b, c]), np.column_stack([a, c, d])])
    return vertices, faces


def vertex_normals(heights, spacing):
    """
    Return the unit surface normal at every grid point, in the same order as the vertices.

    The slope at each point comes from the height differences to its neighbours
    (central differences inside the grid, one-sided at the edges). Gazebo's physics
    engine needs a normal for every vertex of a collision mesh.
    """
    grid = check_heights(heights, spacing)
    dz_dy, dz_dx = np.gradient(grid, spacing)  # rows run along y, columns along x
    normals = np.column_stack([-dz_dx.ravel(), -dz_dy.ravel(), np.ones(grid.size)])
    return normals / np.linalg.norm(normals, axis=1, keepdims=True) + 0.0  # no '-0.0'


def obj_text(vertices, normals, faces):
    """
    Write a mesh in Wavefront OBJ format, with one normal per vertex.

    Indices in the file start at 1. Each face corner refers to vertex i and normal i.
    """
    if len(normals) != len(vertices):
        raise ValueError(f'need one normal per vertex, got {len(normals)} for {len(vertices)}')
    lines = ['# Generated by agri_ugv_terrain']
    lines += [f'v {x:.4f} {y:.4f} {z:.4f}' for x, y, z in vertices]
    lines += [f'vn {x:.4f} {y:.4f} {z:.4f}' for x, y, z in normals]
    lines += [f'f {i + 1}//{i + 1} {j + 1}//{j + 1} {k + 1}//{k + 1}' for i, j, k in faces]
    return '\n'.join(lines) + '\n'


def model_sdf(name, mesh_file):
    """
    Write a static Gazebo model whose collision and visual both use the mesh.

    The wheels touch exactly the surface that is shown: no simplified collision box.
    """
    uri = f'meshes/{mesh_file}'
    return f"""<?xml version="1.0"?>
<sdf version="1.9">
  <model name="{name}">
    <static>true</static>
    <link name="link">
      <collision name="collision">
        <geometry>
          <mesh><uri>{uri}</uri></mesh>
        </geometry>
      </collision>
      <visual name="visual">
        <geometry>
          <mesh><uri>{uri}</uri></mesh>
        </geometry>
        <material>
          <ambient>0.45 0.35 0.25 1</ambient>
          <diffuse>0.45 0.35 0.25 1</diffuse>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""


def model_config(name, description):
    """Write the model.config file that lets Gazebo find the model by name."""
    return f"""<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>{description}</description>
</model>
"""
