"""Command-line tool: generate a terrain model folder for Gazebo."""

import argparse
from pathlib import Path
import re

from agri_ugv_terrain import shapes
from agri_ugv_terrain.heightfield import (mesh_from_heights, model_config, model_sdf,
                                          obj_text, vertex_normals)


def write_model(directory, name, heights, spacing, description):
    """
    Write <directory>/<name>/ with model.config, model.sdf and meshes/<name>.obj.

    Returns the path of the model folder. The name is used in file paths and XML,
    so it may only contain letters, digits and underscores.
    """
    if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', name):
        raise ValueError(f'model name must be letters, digits and underscores, got {name!r}')
    vertices, faces = mesh_from_heights(heights, spacing)
    model_dir = Path(directory) / name
    (model_dir / 'meshes').mkdir(parents=True, exist_ok=True)
    normals = vertex_normals(heights, spacing)
    (model_dir / 'meshes' / f'{name}.obj').write_text(obj_text(vertices, normals, faces))
    (model_dir / 'model.sdf').write_text(model_sdf(name, f'{name}.obj'))
    (model_dir / 'model.config').write_text(model_config(name, description))
    return model_dir


def main(argv=None):
    """Parse the command line, build the height grid and write the model."""
    parser = argparse.ArgumentParser(description='Generate a terrain model for Gazebo.')
    parser.add_argument('--shape', choices=['flat', 'waves'], required=True, help='terrain shape')
    parser.add_argument('--name', required=True, help='model name, e.g. flat_mesh')
    parser.add_argument('--length', type=float, default=20.0, help='size along x (m)')
    parser.add_argument('--width', type=float, default=20.0, help='size along y (m)')
    parser.add_argument('--spacing', type=float, default=0.5, help='grid spacing (m)')
    parser.add_argument('--amplitude', type=float, default=0.05, help='waves: crest height (m)')
    parser.add_argument('--wavelength', type=float, default=2.7, help='waves: crest to crest (m)')
    parser.add_argument('--output-dir', default='.', help='folder that receives the model')
    args = parser.parse_args(argv)

    if args.shape == 'flat':
        heights = shapes.flat(args.length, args.width, args.spacing)
        details = ''
    else:
        heights = shapes.waves(args.length, args.width, args.spacing,
                               args.amplitude, args.wavelength)
        details = f', waves along x +-{args.amplitude:g} m every {args.wavelength:g} m'
    description = (f'{args.shape} test terrain, {args.length:g} x {args.width:g} m, '
                   f'{args.spacing:g} m grid{details}; generated by agri_ugv_terrain')
    model_dir = write_model(args.output_dir, args.name, heights, args.spacing, description)
    rows, cols = heights.shape
    print(f'Wrote {model_dir}: {rows} x {cols} points, {2 * (rows - 1) * (cols - 1)} triangles')
