"""Command-line tool: generate a terrain model folder for Gazebo."""

import argparse
from pathlib import Path
import re

from agri_ugv_terrain import shapes
from agri_ugv_terrain.heightfield import (cell_centre_uvs, mesh_from_heights, model_config,
                                          model_sdf, mtl_text, obj_text, vertex_normals)
import numpy as np


def write_model(directory, name, heights, spacing, description, texture=None):
    """
    Write <directory>/<name>/ with model.config, model.sdf and meshes/<name>.obj.

    Returns the path of the model folder. The name is used in file paths and XML,
    so it may only contain letters, digits and underscores. An optional texture (an RGB
    image covering the whole grid, north at the top) adds meshes/<name>.jpg and .mtl.
    """
    if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', name):
        raise ValueError(f'model name must be letters, digits and underscores, got {name!r}')
    vertices, faces = mesh_from_heights(heights, spacing)
    model_dir = Path(directory) / name
    (model_dir / 'meshes').mkdir(parents=True, exist_ok=True)
    normals = vertex_normals(heights, spacing)
    if texture is None:
        obj = obj_text(vertices, normals, faces)
    else:
        from PIL import Image  # only needed for textured terrains
        Image.fromarray(np.asarray(texture, dtype=np.uint8)).save(
            model_dir / 'meshes' / f'{name}.jpg', quality=85)
        (model_dir / 'meshes' / f'{name}.mtl').write_text(mtl_text(name, f'{name}.jpg'))
        obj = obj_text(vertices, normals, faces, cell_centre_uvs(*np.shape(heights)), name)
    (model_dir / 'meshes' / f'{name}.obj').write_text(obj)
    (model_dir / 'model.sdf').write_text(model_sdf(name, f'{name}.obj', texture is not None))
    (model_dir / 'model.config').write_text(model_config(name, description))
    return model_dir


def dem_heights(args):
    """Read the DEM file and return (heights, description) for a terrain from real survey data."""
    from agri_ugv_terrain import dem  # needs rasterio, so only imported for DEM terrains

    raw, valid, pixel, left, top, crs = dem.read_dem(args.dem_file)
    block = round(args.spacing / pixel)
    if block < 1 or abs(block * pixel - args.spacing) > 1e-6:
        raise ValueError(f'spacing ({args.spacing} m) must be a whole multiple of the '
                         f'DEM pixel size ({pixel:g} m)')
    heights, reference = dem.heights_from_dem(raw, valid, block, args.percentile)
    rows, cols = heights.shape
    texture = None
    if args.ortho_file:
        rgb, photo_pixel, photo_left, photo_top = dem.read_ortho(args.ortho_file)
        if (rgb.shape[:2] != raw.shape or abs(photo_pixel - pixel) > 1e-6
                or abs(photo_left - left) > 1e-3 or abs(photo_top - top) > 1e-3):
            raise ValueError('the photo must have exactly the same pixel grid as the DEM')
        texture = dem.texture_from_ortho(rgb, block, rows, cols, args.texture_factor)
    east = left + cols * block * pixel / 2.0
    north = top - rows * block * pixel / 2.0
    description = (f'terrain from {Path(args.dem_file).name}, {args.spacing:g} m grid, '
                   f'{args.percentile:g}th height percentile per cell; origin at {crs} '
                   f'E {east:.2f} N {north:.2f}, {reference:.3f} m above sea level; '
                   f'generated by agri_ugv_terrain')
    if texture is not None:
        description += f'; texture from {Path(args.ortho_file).name}'
    return heights, description, texture


def main(argv=None):
    """Parse the command line, build the height grid and write the model."""
    parser = argparse.ArgumentParser(description='Generate a terrain model for Gazebo.')
    parser.add_argument('--shape', choices=['flat', 'waves', 'ramp', 'dem'], required=True,
                        help='terrain shape')
    parser.add_argument('--name', required=True, help='model name, e.g. flat_mesh')
    parser.add_argument('--length', type=float, default=20.0, help='size along x (m)')
    parser.add_argument('--width', type=float, default=20.0, help='size along y (m)')
    parser.add_argument('--spacing', type=float, default=0.5, help='grid spacing (m)')
    parser.add_argument('--amplitude', type=float, default=0.05, help='waves: crest height (m)')
    parser.add_argument('--wavelength', type=float, default=2.7, help='waves: crest to crest (m)')
    parser.add_argument('--grade', type=float, default=0.10, help='ramp: rise over run')
    parser.add_argument('--dem-file', help='dem: GeoTIFF elevation map')
    parser.add_argument('--ortho-file', help='dem: aerial photo (GeoTIFF) used as texture')
    parser.add_argument('--texture-factor', type=int, default=2,
                        help='dem: shrink the photo by this factor (2: 3 cm -> 6 cm pixels)')
    parser.add_argument('--percentile', type=float, default=10.0,
                        help='dem: height percentile per cell (low = soil between plants)')
    parser.add_argument('--output-dir', default='.', help='folder that receives the model')
    args = parser.parse_args(argv)

    texture = None
    if args.shape == 'flat':
        heights = shapes.flat(args.length, args.width, args.spacing)
        description = (f'flat test terrain, {args.length:g} x {args.width:g} m, '
                       f'{args.spacing:g} m grid; generated by agri_ugv_terrain')
    elif args.shape == 'waves':
        heights = shapes.waves(args.length, args.width, args.spacing,
                               args.amplitude, args.wavelength)
        description = (f'waves test terrain, {args.length:g} x {args.width:g} m, '
                       f'{args.spacing:g} m grid, waves along x +-{args.amplitude:g} m '
                       f'every {args.wavelength:g} m; generated by agri_ugv_terrain')
    elif args.shape == 'ramp':
        heights = shapes.ramp(args.length, args.width, args.spacing, args.grade)
        description = (f'ramp test terrain, {args.length:g} x {args.width:g} m, '
                       f'{args.spacing:g} m grid, grade {100 * args.grade:g} % along x; '
                       f'generated by agri_ugv_terrain')
    else:
        if not args.dem_file:
            parser.error('--shape dem needs --dem-file')
        heights, description, texture = dem_heights(args)
    model_dir = write_model(args.output_dir, args.name, heights, args.spacing, description,
                            texture)
    rows, cols = heights.shape
    print(f'Wrote {model_dir}: {rows} x {cols} points, {2 * (rows - 1) * (cols - 1)} triangles, '
          f'heights {heights.min():+.3f} to {heights.max():+.3f} m')
    print(description)
